### PR TITLE
Allow compatibility with Laravel 10 (and Passport 11)

### PR DESCRIPTION
**Pull request by omitobi**
1. Now requires passport 11 (opt in)
2. Routes are declared in a dedicated web.php file
3. RouteRegistrar are left for backward compatibility
4. Remove composer.lock file

**Todo**

1. Tests are failing. I couldn't get it to pass @arietimmerman can you help with this?

### CODE REVIEW

**Comment by arietimmerman** [comment]
Thanks! I will check it out and see if I can fix the failing tests.

**Comment by arietimmerman** [comment]
This should fix it: https://github.com/eideasy/laravel-openid-connect-server/pull/1

**Comment by omitobi** [comment]
@arietimmerman I have merged your changes into this Pull Request.

**Comment by arietimmerman** [comment]
Thanks!

**Pull request merged**
