### PR TITLE
Support for Laravel Passport 11 #19

### PR DESCRIPTION
**Pull request by arietimmerman**

### CODE REVIEW

**Comment by omitobi** [comment]
@arietimmerman Are you planning to update this soon or you need help with it?

**Comment by arietimmerman** [comment]
Hi @omitobi , this is for sure on my list. If you could provide a little help, that would be nice. I'll send you a message.

**Comment by omitobi** [comment]
Once you release the updates to https://github.com/limosa-io/openid-connect-server then I can send a pull request for this.

**Comment by omitobi** [comment]
I already have a draft branch that I need to fine-tune and I can submit a Pull Request for.

**Comment by arietimmerman** [comment]
> Once you release the updates to https://github.com/limosa-io/openid-connect-server then I can send a pull request for this.

I think I did already :)

**Comment by omitobi** [comment]
I sent the PR for Passport 11 here: https://github.com/limosa-io/laravel-openid-connect-server/pull/26

**Pull request closed without merging**
